name: defi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  #sdk: '>=2.18.2 <3.0.0'
  sdk: '>=3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  lottie: ^1.4.3
  web3dart: ^2.4.1  
  http: ^0.13.5
  path: ^1.8.2
  web_socket_channel: ^2.2.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.2.1
  pin_code_fields: ^7.4.0
  flutter_screenutil: ^5.6.0
  flutter_custom_clippers: ^2.0.0
  animated_bottom_navigation_bar: ^1.1.0
  fl_chart: ^0.55.2
  crypto_font_icons: ^1.0.1
  qr_flutter: ^4.0.0
  permission_handler: ^10.2.0
  qr_code_scanner: ^1.0.1
  built_value: ^8.4.2
  ed25519_hd_key: ^2.2.0
  bip39: ^1.0.6
  shared_preferences: ^2.1.2
  hex: ^0.2.0
  provider: ^6.0.4
  firebase_core: ^2.3.0
  google_sign_in: ^5.4.2
  firebase_auth: ^4.1.5
  email_auth: ^1.0.0
  loader_overlay: ^2.1.0
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  flutter_hooks: ^0.18.5+1
  share_plus: ^6.3.0
  intl: ^0.19.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  cloud_firestore: ^4.9.1
  bloc: ^8.1.2
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.3
  loading_animation_widget: ^1.2.0+4
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  awesome_notifications: ^0.9.2
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  built_value_generator: ^8.4.2
  build_runner: ^2.3.2
  logger: ^1.1.0
  mockito: ^5.4.2
  freezed: ^2.4.6
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/payment/
    - assets/fonts/
    - assets/images/
    - assets/cryptos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

    - family: RobotoCondensed
      fonts: 
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
    
    - family: RobotoCondensed-Bold
      fonts: 
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 900

    - family: RobotoCondensed-Italic
      fonts:
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic

    - family: MonstSerrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Weigth.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
